blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/njfamirm/alwatr-community/discussions
    about: Please ask and answer questions here.

  - name: Contact up
    url: 'https://t.me/njfamirm'
    about: Direct contact to Alwatr support team at Telegram.
